"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-5lv9q*#&i0rnk^x7w^67p#$$=!ydz&6h-(eimd$m%wj4%ljvh6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

# Render.com deployment
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
ALLOWED_HOSTS = ['localhost', '127.0.0.1']
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
if DEBUG:
    ALLOWED_HOSTS.append('*')  # Allow all hosts in development

# CSRF trusted origins for Render
CSRF_TRUSTED_ORIGINS = []
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.hamsalert',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.middleware.AdminIPRestrictMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# SQLite: increase lock timeout from 5s to 30s
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['timeout'] = 30


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Cache configuration (database backend, works with SQLite)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'django_cache_table',
    }
}


# AVWX Weather API
AVWX_API_TOKEN = os.environ.get('AVWX_API_TOKEN', '')
AVWX_DEFAULT_STATION = 'KACV'  # Arcata-Eureka Airport (near Samoa)

# NWS API Configuration
NWS_DEFAULT_LOCATION = (40.9781, -124.1086)  # Lat/lon near KACV
NWS_USER_AGENT = 'HamsAlert/1.0'

# Local timezone for weather date comparisons
WEATHER_LOCAL_TIMEZONE = 'America/Los_Angeles'

# Visual Crossing API Key (for extended forecasts)
# Get a free API key at https://www.visualcrossing.com/sign-up
VISUALCROSSING_API_KEY = os.environ.get('VISUALCROSSING_API_KEY', '')

# Weather Cache TTLs
WEATHER_METAR_CACHE_TTL = 1800   # 30 min
WEATHER_TAF_CACHE_TTL = 3600    # 1 hour
WEATHER_NWS_CACHE_TTL = 7200    # 2 hours
WEATHER_VISUALCROSSING_CACHE_TTL = 14400  # 4 hours

# Weather API Request Settings (retry on failures)
WEATHER_MAX_RETRIES = 3
WEATHER_BASE_DELAY = 1.0  # seconds
WEATHER_MAX_DELAY = 30.0  # seconds

# Weather API Rate Limits
WEATHER_RATE_LIMIT_PER_MINUTE = 600
WEATHER_RATE_LIMIT_PER_HOUR = 5000
WEATHER_RATE_LIMIT_PER_DAY = 10000
WEATHER_RATE_LIMIT_SAFETY_MARGIN = 0.9

# Weather DB Storage
WEATHER_DB_CLEANUP_DAYS = 30  # Delete records older than this

# Scheduler Settings
SCHEDULER_CLEANUP_HOUR = 3  # Run cleanup at 3am local time

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'apps.hamsalert.services.weather': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.hamsalert.weather_poller': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
