# Generated by Django 6.0.1 on 2026-01-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['date', 'club'],
            },
        ),
    ]
