# Generated by Django 6.0.1 on 2026-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamsalert', '0002_load_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.CharField(choices=[('metar', 'METAR'), ('taf', 'TAF'), ('nws', 'NWS'), ('openmeteo', 'Open-Meteo'), ('hourly', 'Hourly'), ('historical', 'Historical')], db_index=True, max_length=20)),
                ('target_date', models.DateField(db_index=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('station', models.CharField(blank=True, db_index=True, max_length=10)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['weather_type', 'target_date', 'station'], name='weather_lookup_idx'), models.Index(fields=['weather_type', 'target_date', 'latitude', 'longitude'], name='weather_location_idx')],
            },
        ),
    ]
