# Generated by Django 6.0.1 on 2026-01-29 15:38

from django.db import migrations, models
from django.db.models import Count


def cleanup_duplicate_weather_records(apps, schema_editor):
    """
    Remove duplicate WeatherRecord entries before adding unique constraint.
    Keeps the most recent record (by fetched_at) for each unique combination.
    """
    WeatherRecord = apps.get_model('hamsalert', 'WeatherRecord')

    # Find duplicate groups
    duplicates = WeatherRecord.objects.values(
        'weather_type', 'target_date', 'station', 'latitude', 'longitude'
    ).annotate(count=Count('id')).filter(count__gt=1)

    total_deleted = 0
    for dup in duplicates:
        # Get all records in this duplicate group, ordered by fetched_at descending
        records = WeatherRecord.objects.filter(
            weather_type=dup['weather_type'],
            target_date=dup['target_date'],
            station=dup['station'],
            latitude=dup['latitude'],
            longitude=dup['longitude']
        ).order_by('-fetched_at')

        # Keep the first (most recent), delete the rest
        ids_to_delete = list(records.values_list('id', flat=True)[1:])
        if ids_to_delete:
            WeatherRecord.objects.filter(id__in=ids_to_delete).delete()
            total_deleted += len(ids_to_delete)

    if total_deleted:
        print(f'\n  Cleaned up {total_deleted} duplicate WeatherRecord entries')


def noop(apps, schema_editor):
    """No-op for reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hamsalert', '0003_add_weather_record_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecord',
            name='fetched_at',
            field=models.DateTimeField(db_index=True),
        ),
        # Clean up duplicates BEFORE adding the unique constraint
        migrations.RunPython(cleanup_duplicate_weather_records, noop),
        migrations.AddConstraint(
            model_name='weatherrecord',
            constraint=models.UniqueConstraint(fields=('weather_type', 'target_date', 'station', 'latitude', 'longitude'), name='weather_unique_record'),
        ),
    ]
