# Generated by Django 6.0.1 on 2026-01-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamsalert', '0004_weather_record_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyingIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'session_key'), name='unique_flying_intent_per_session_date')],
            },
        ),
    ]
